apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-alqj
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0037-tenant/tkrw-pr712-0075-0037-app/devfile-sample-alqj@sha256:4860d5e5fe9511f9e4dc84a53395397db5e77e2b2d1fa39fd449a6be6c07875e
        name: my-nodejs
        resources: {}
status: {}
